#logging:
#  file:
#    name: ${logging.file.path}/shop-product.log
#    path: /var/log/shop
#server:
#  port: 8082
#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/shop_product?characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456