spring:
  application:
    name: shop-product
  cloud:
    nacos:
      config:
        file-extension: yaml
        group: PRODUCT_GROUP
        namespace: ${spring.profiles.active}
      discovery:
        namespace: ${spring.profiles.active}
      server-addr: nacos:8848
  config:
    import: nacos:shop-product.yaml
  profiles:
    active: dev