server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop_order?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
