spring:
  application:
    name: shop-order
  cloud:
    nacos:
      config:
        file-extension: yaml
        group: ORDER_GROUP
        namespace: ${spring.profiles.active}
      discovery:
        namespace: ${spring.profiles.active}
      server-addr: nacos:8848
  config:
    import: nacos:shop-order.yaml
  profiles:
    active: dev