#logging:
#  file:
#    name: ${logging.file.path}/shop-gateway.log
#    path: /var/log/shop
#server:
#  port: 8080
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"