spring:
  application:
    name: shop-gateway
  cloud:
    nacos:
      config:
        file-extension: yaml
        group: GATEWAY_GROUP
        namespace: ${spring.profiles.active}
      discovery:
        namespace: ${spring.profiles.active}
      server-addr: 127.0.0.1:8848
  config:
    import: nacos:shop-gateway.yaml
  profiles:
    active: dev