server:
  port: 8080
spring:
  application:
    name: shop-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    nacos:
      server-addr: 127.0.0.1:8848

