spring:
  application:
    name: shop-user
  cloud:
    nacos:
      config:
        file-extension: yaml
        group: USER_GROUP
        namespace: ${spring.profiles.active}
      discovery:
        namespace: ${spring.profiles.active}
      server-addr: 127.0.0.1:8848
  config:
    import: nacos:shop-user.yaml
  profiles:
    active: dev