#logging:
#  file:
#    name: ${logging.file.path}/shop-user.log
#    path: /var/log/shop
#server:
#  port: 8081
#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/shop_user?characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans